repeat = {type = "repeat", params = ["render_module", 1]}
render_module = {type = "render", params = ["repeat_test_", "joe_buffer", "audio"]}
joe_buffer = {type = "buffer", params = ["noise", "audio", 4410]}
noise = {type = "noise", params = []}
