repeater = {type = "repeat", params = ["render_module", 2]}
render_module = {type = "render", params = ["repeat_test_", "joe_buffer", "audio"]}
joe_buffer = {type = "buffer", params = ["static", "audio", 11025]}
static = {type = "param", params = [0.33]}